#!/usr/bin/env python3
"""unitv_bundle.py - Bundle the Unit V firmware into a single boot.py.

WHY: the MaixPy v0.5.0 build on this Unit V reliably execs /flash/boot.py at
boot, but FURTHER file opens during boot fail deterministically for some files
(OSError ENOENT for /flash/uart_protocol.py, 12/12 attempts, while the same
file reads fine from the REPL). Instead of fighting that SPIFFS quirk, this
script embeds config.py / uart_protocol.py / detector.py / main.py as source
strings inside one generated boot.py: at boot each is exec'd from RAM into a
namespace object registered in sys.modules, so `import config` etc. resolve
without touching the filesystem at all. Zero boot-time file reads.

The individual .py files in meshscan/unitv/ stay the source of truth — edit
those, re-run this, push the generated boot.py:

    python unitv_bundle.py                # writes ../unitv/build/boot.py
    python -m ampy.cli -p COM10 -b 115200 -d 0.5 put ../unitv/build/boot.py /flash/boot.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "unitv"))
OUT_DIR = os.path.join(SRC, "build")
MODULES = ["config", "uart_protocol", "detector"]   # dependency order
MAIN = "main"

HEADER = '''\
# boot.py - MeshScan Unit V firmware, single-file bundle. DO NOT EDIT.
# Generated by meshscan/tools/unitv_bundle.py from the individual module
# files in meshscan/unitv/ (edit those and re-run the bundler instead).
#
# All module sources are embedded below and exec'd from RAM: this build of
# MaixPy v0.5.0 fails deterministically on some boot-time file opens, so the
# firmware performs ZERO filesystem reads at boot. Modules are registered in
# sys.modules, so `import config` etc. inside the code resolve from RAM.
# Side benefit: nothing on the SD card can ever shadow firmware modules.

import sys


class _NS:
    pass


def _register(name, src):
    g = {"__name__": name}
    exec(src, g)
    ns = _NS()
    for k in g:
        setattr(ns, k, g[k])
    sys.modules[name] = ns
    print("[boot] loaded", name)


'''

FOOTER = '''
try:
'''

FOOTER_END = '''\
    print("[boot] modules registered, starting main")
    exec(_SRC_MAIN)
except KeyboardInterrupt:
    pass                      # Ctrl-C drops to the REPL
except Exception as e:
    print("[boot] main stopped:", repr(e))
    sys.print_exception(e)
'''


def embed(name, path):
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    # Pick a triple-quote delimiter that doesn't appear in the source.
    for q in ('"""', "'''"):
        if q not in src and not src.rstrip().endswith(q[0]):
            return f'_SRC_{name.upper()} = {q}\\\n{src}{q}\n\n'
    raise SystemExit(f"{path}: contains both triple-quote styles; not supported")


def main():
    parts = [HEADER]
    for m in MODULES + [MAIN]:
        p = os.path.join(SRC, m + ".py")
        parts.append(embed(m, p))
        print(f"embedded {m}.py ({os.path.getsize(p)} bytes)")
    parts.append(FOOTER)
    for m in MODULES:
        parts.append(f'    _register("{m}", _SRC_{m.upper()})\n')
    parts.append(FOOTER_END)

    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, "boot.py")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(parts))
    print(f"wrote {out} ({os.path.getsize(out)} bytes)")
    # sanity: the generated file must itself be valid python
    compile(open(out, encoding="utf-8").read(), out, "exec")
    print("syntax check OK")


if __name__ == "__main__":
    main()
